# Generated by Django 3.0.6 on 2020-05-17 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='expiresAt',
            new_name='expiresIn',
        ),
        migrations.AlterField(
            model_name='user',
            name='userId',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
